core/urls.py
from django.urls import path
import core.views as coreviews
import core.htmx as htmxviews

urlpatterns = [
    path('', coreviews.HomeView.as_view(), name='home'),
    path('project/<int:project_id>', coreviews.ProjectView.as_view(), name='project'),
    path('projects/', coreviews.ProjectListView.as_view(), name='projects'),
    path('projects/language/<int:language_id>', coreviews.ProjectListView.as_view(), name='projects'),
    path('projects/technology/<int:technology_id>', coreviews.ProjectListView.as_view(), name='projects'),
    path('project/image/<int:projectimage_id>', coreviews.Project_Image_Download.as_view(), name='project-image-download'),
    path('career/', coreviews.CareerView.as_view(), name='career'),
    path('site/', coreviews.SiteView.as_view(), name='site'),
    path('results/', coreviews.ResultsView.as_view(), name='results'),
    path('get-modal-content/', htmxviews.get_modal_content, name='get-modal-content' ),
    path('get-modal-content/<str:param1>/', htmxviews.get_modal_content, name='get-modal-content' ),
    path('switch-user/', htmxviews.switch_user, name='switch-user' ),
    path('mark-done/', htmxviews.mark_done, name='mark-done' ),
    
    path('about_me/', coreviews.AboutMeView.as_view(), name='about_me'),
    path('webhooks/', coreviews.Webhooks.as_view(), name='webhooks'),
    # path('enquiries/', coreviews.EnquiriesView.as_view(), name='enquiries'),
    # path('iot/', coreviews.IotView.as_view(), name='iot'),
    # path('energy-chart/', coreviews.energy_chart, name='energy-chart'),

    # path('test/', coreviews.test, name='test'),
    path('leads-management-privacy-policy/', coreviews.LeadsManagementPrivacyPolicy.as_view(), name='leads-management-privacy-policy'),

]

urls.py
from django.urls import path
from django.contrib import admin
import core.urls
from django.urls import include, path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from  rest_framework.authtoken.views import obtain_auth_token
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(core.urls)),
    path('api/auth/', obtain_auth_token),
    path('api/', include('api.routers'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.db.models.deletion import SET_NULL
from django.contrib.auth.models import User


# Extending User Model Using a One-To-One Link
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='default.jpg', upload_to='profile_images')

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"

class HomeDevice(models.Model):
    sw_ver = models.CharField(null = True, max_length = 225, blank=True)
    hw_ver = models.CharField(null = True, max_length = 225, blank=True)
    type = models.CharField(null = True, max_length = 225, blank=True)
    hwId = models.CharField(null = True, max_length = 225, blank=True)
    fwId = models.CharField(null = True, max_length = 225, blank=True)
    oemId = models.CharField(null = True, max_length = 225, blank=True)
    dev_name = models.CharField(null = True, max_length = 225, blank=True)
    alias = models.CharField(null = True, max_length = 225, blank=True)
    updated = models.DateTimeField(auto_now=True)
    mac = models.CharField(max_length = 225, unique=True)

    def __str__(self):
        return self.dev_name

class HomePlug(HomeDevice):

    def __str__(self):
        return self.dev_name

class EnergyDayReading(models.Model):
    homeplug = models.ForeignKey(HomePlug, on_delete=models.CASCADE)
    date = models.DateField(null=True, blank=True)
    nice_date = models.CharField(null = True, max_length = 225, blank=True)
    energy_wh = models.IntegerField(null = True, blank=True)


class TechnologyType(models.Model):
    name = models.CharField(null = True, max_length = 225, blank=True)

    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(null = True, max_length = 225, blank=True)

    def __str__(self):
        return self.name


class Technology(models.Model):
    name = models.CharField(null = True, max_length = 225, blank=True)
    type = models.ManyToManyField(TechnologyType, null = True, blank=True)
    language = models.ManyToManyField(Language, null = True, blank=True)
    image = models.FileField(null = True, blank=True, upload_to='technology-images')
    priority = models.IntegerField(default=100)
    htmldescription = models.CharField(null = True, max_length = 500, blank=True)

    def __str__(self):
        return self.name

    
class Project(models.Model):
    name = models.CharField(null = True, max_length = 225, blank=True)
    start = models.DateField(null=True, blank=True)
    end = models.DateField(null=True, blank=True)
    technology = models.ManyToManyField(Technology, blank=True)
    htmldescription = models.CharField(null = True, max_length = 4000, blank=True)
    shorthtmldescription = models.CharField(null = True, max_length = 1000, blank=True)
    role = models.CharField(null = True, max_length = 500, blank=True)
    teamsize = models.IntegerField(null = True, blank=True)

    def __str__(self):
        return self.name
    def get_languages(self):
        return Language.objects.filter(technology__in=self.technology.all()).distinct('pk')
    
class ProjectImage(models.Model):
    image = models.FileField(null = True, upload_to='technology-images')
    htmldescription = models.CharField(null = True, max_length = 5000, blank=True)
    project = models.ManyToManyField(Project, null=True, blank=True)
    priority = models.IntegerField(default=100)
    show_on_demo = models.BooleanField(default=False)

    class Meta:
        ordering = ['priority']

    

core/views.py
from sys import version
from django.views.generic import TemplateView
from core.models import Technology, TechnologyType, Project, ProjectImage, Language, HomePlug, EnergyDayReading
from django.views import View
from django.http import HttpResponse
import os

import asyncio
# from kasa import SmartPlug
from asgiref.sync import sync_to_async
import datetime
from django.shortcuts import render
from django.db.models import Sum
from django.http import JsonResponse
import logging
from django.db.models import F  
logger = logging.getLogger(__name__)


# class IotView(TemplateView):
#     template_name='core/iot.html'

#     def get_context_data(self, **kwargs):
#         context = super(IotView, self).get_context_data(**kwargs)
#         return context

# def energy_chart(request):
#     labels = []
#     data = []

#     queryset = EnergyDayReading.objects.values('nice_date').annotate(homedevice_mac=Sum('energy_wh')).order_by('date')
#     for entry in queryset:
#         labels.append(entry['nice_date'])
#         data.append(entry['homedevice_mac'])
    
#     return JsonResponse(data={
#         'labels': labels,
#         'data': data,
#     })

# async def updateKasa(ip):
#     p = SmartPlug(ip)
    
#     await p.update()
#     await p.turn_off()
#     return p

# def getLastMonth(datetime):
#     month = datetime.month
#     year = datetime.year
#     if month == 1:
#         month = 12
#         year = year - 1
#     return month, year

class HomeView(TemplateView):
    template_name='core/home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        
        # try:
            
            # plug = asyncio.run(updateKasa("192.168.0.29"))
            # existing_plug, created = HomePlug.objects.get_or_create(mac=plug.hw_info['mac'])

            # existing_plug.sw_ver=plug.hw_info['sw_ver']
            # existing_plug.hw_ver=plug.hw_info['hw_ver'],
            # existing_plug.hwId=plug.hw_info['hwId'],
            # existing_plug.oemId=plug.hw_info['oemId'],
            # existing_plug.dev_name=plug.hw_info['dev_name'],
            # existing_plug.alias=plug.alias
            # existing_plug.save()

            # month, year = getLastMonth(datetime.datetime.now())
            # temp = asyncio.run(plug.get_emeter_daily(year=year, month=month, kwh=False))
            # for k, v in temp.items():
            #     logger.debug(datetime.datetime(year, month, k))
            #     existing_reading, created = EnergyDayReading.objects.get_or_create(date = datetime.datetime(year, month, k), homeplug=existing_plug)
            #     existing_reading.energy_wh=v
            #     existing_reading.nice_date=existing_reading.date.strftime('%A %d %B %Y')
            #     existing_reading.save()
        # except Exception as e:
        #     logger.debug("ERROR "+str(e))


        # context['kasa'] = plug
        context['technologies'] = Technology.objects.all().order_by('priority')
        return context

class ProjectListView(TemplateView):
    template_name='core/projectlist.html'

    def get_context_data(self, **kwargs):

        context = super(ProjectListView, self).get_context_data(**kwargs)
        context['projectlist'] = Project.objects.all().order_by(F('end').desc(nulls_first=True))
        if 'technology_id' in kwargs:
            filter_technology = Technology.objects.filter(pk=kwargs['technology_id']).first()
            context['projectlist'] = context['projectlist'].filter(technology=filter_technology)
            context['filter_type'] = 'Technology'
            context['filter_parameter'] = filter_technology.name
        if 'language_id' in kwargs:
            filter_language = Language.objects.filter(pk=kwargs['language_id']).first()
            context['projectlist'] = context['projectlist'].filter(technology__language=filter_language)
            context['filter_type'] = 'Language'
            context['filter_parameter'] = filter_language.name
            
        return context

class ProjectView(TemplateView):
    template_name='core/project.html'

    def get_context_data(self, **kwargs):

        context = super(ProjectView, self).get_context_data(**kwargs)
        context['project'] = Project.objects.filter(pk=kwargs['project_id']).first() 
        return context

class CareerView(TemplateView):
    template_name='core/career.html'

    def get_context_data(self, **kwargs):
        context = super(CareerView, self).get_context_data(**kwargs)
        return context

class SiteView(TemplateView):
    template_name='core/site.html'

    def get_context_data(self, **kwargs):
        context = super(SiteView, self).get_context_data(**kwargs)
        return context
class ResultsView(TemplateView):
    template_name='core/results.html'

    def get_context_data(self, **kwargs):
        context = super(ResultsView, self).get_context_data(**kwargs)
        return context

class Project_Image_Download(View):
    def get(self, request, **kwargs):
        projectimage = ProjectImage.objects.filter(pk=kwargs['projectimage_id']).first()
        if projectimage:
            httpresponse = HttpResponse(projectimage.image.file, content_type='application/force-download')
            httpresponse['Content-Disposition'] = 'attachment; filename="'+projectimage.project.name+' Screenshot'+os.path.splitext(projectimage.image.file.name)[1]+'"'
            return httpresponse

# class EnquiriesView(TemplateView):
#     template_name='core/enquiries.html'

#     def get_context_data(self, **kwargs):
#         context = super(EnquiriesView, self).get_context_data(**kwargs)
#         return context
class AboutMeView(TemplateView):
    template_name='core/about_me.html'

    def get_context_data(self, **kwargs):
        context = super(AboutMeView, self).get_context_data(**kwargs)
        return context

from django.core.mail import send_mail
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
import json
@method_decorator(csrf_exempt, name="dispatch")
class Webhooks(View):
    def get(self, request, *args, **kwargs):
        send_mail(
            'Webhook',
            f"{str(request)}",
            'jobiewinser@localhost',
            ['jobiewinser@live.co.uk'],
            fail_silently=False,
        )
        return HttpResponse(f"EVENT_RECEIVED",status_code=200)

    def post(self, request, *args, **kwargs):
        temp_string = f"POST {request.build_absolute_uri()}<br>"
        for k,v in json.loads(request.body).items():
            temp_string = temp_string + f"{k}: {v} <br>"
        print(temp_string)
        logger.debug("temp_string "+str(temp_string))
        challenge = json.loads(request.body).get('hub.challenge',{})
        response = HttpResponse(challenge)
        response.status_code = 200
        return response

class LeadsManagementPrivacyPolicy(TemplateView):
    template_name='core/leads_management_privacy_policy.html'

    def get_context_data(self, **kwargs):
        context = super(LeadsManagementPrivacyPolicy, self).get_context_data(**kwargs)
        return context

templates/core/about_me.html
{% extends 'core/base.html' %}
{%load static%}
{%block scripts%}
    {{block.super}}
    <script>
        $(document).ready(function() {
            
        });

    </script>
{%endblock scripts%}

{%block styles%}
    {{block.super}}
    <style>
        h5{   
            font-weight: bold;       
        }
        img{
            max-width:250px;         
        }
    </style>
{%endblock styles%}

{% block about_me_active %}active{%endblock about_me_active%}

{%block content%}
    <div class="layout-margin-custom">
        <div class="row">        
            <div class="col-sm p-1" style="min-width:500px">
                <div class="card main-card" style="margin-right:0px">
                    <div class="card-header center">
                        Professional Details
                    </div>
                    <div class="card-body row" style="">
                        <div class="col-md-auto">
                            <img src="{% static '/img/professional_profile.jpg' %}"/>
                            <div class="mt-4" style="text-align:center">
                                <h5>Jobie Winser</h5>
                                <b>Lead Full Stack Developer</b>
                            </div>
                        </div>
                        <div class="col">
                            <h5>Graduation and first role</h5>
                            <p>My name is Jobie Winser and I am a web developer working as the lead developer as Abingdon School. 
                                I graduated from Cardiff University and immediately started looking for work during the height of the COVID-19 pandemic. 
                                After interviewing with my current manager, Niki Dinsey, I secured a job in Abingdon, Oxfordshire and relocated.</p>
                            <h5>My next role</h5>
                            <p>I am looking to move to a more demanding role which will challenge me and further develop my skills by around September 2023.
                                In my current position I must give a 3 month notice before taking a new position, however this is likely negotiable (especially closer to September 2023).
                            </p>
                            <p>My ideal role would be python based working either as a backend or full stack developer. I am, however, open to most development roles.  
                                I find that my backend work is my most effective as my previous systems are mostly internal and focused on function over form.
                            </p>
                            <h5>Location</h5>
                            <p>Finally, I am willing to work pretty much anywhere. Relocation is possible, although I'd prefer to have the option to work remotely for high living-cost areas.
                            </p>
                        </div>
                    </div>
                </div>
            </div>       
            <div class="col-sm p-1" style="min-width:500px">
                <div class="card main-card" style="margin-right:0px">
                    <div class="card-header center">
                        Personal Details
                    </div>
                    <div class="card-body row" style="">
                        <div class="col-md-auto">
                            <img src="{% static '/img/personal_profile.jpg' %}"/>
                        </div>
                        <div class="col">
                            <h5>Me</h5>
                            <p>I'm a high energy, and passionate individual, especially when something takes my interest and requires a new approach to solve. You'll find that i'm quiet when I'm deep in a project but talkative otherwise.</p>
                            <p>I take pride in my ability to include anyone and everyone in discussion and value the varying life experiences others have when weighing in on a topic.</p>
                            <h5>Hobbies - Powerlifting / Body Building</h5>
                            <p>My main non-professional goal for the last couple of years has been to deadlift 200kg and achieved this while weighing 83 kg.
                                Once I had achieved this, I moved from powerlifting to body building and typically spend approximately 9 hours a week in the gym.</p>
                            <h5>Hobbies - Devops</h5>
                            <p>A large amount of my time is spent tinkering with old server equipment and my proxmox machine. 
                                There's always a project or a game server that needs hosting after all.</p>
                            <h5>Hobbies - Video Games / Wargaming</h5>
                            <p>I'm a huge fan of competitive games such as DOTA 2 along with slower paced games such as Dawn of War, Rimworld, Empire Earth, Starsector etc. I find it very easy to talk about gaming and is often a great starting point of conversation for me.</p>
                            <p>I'm also a casual fan of table top games such as Warhammer 40k and Age of Sigmar along with role playing games such as Dungeons & Dragons.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{%endblock content%}

templates/core/home.html
{% extends 'core/base.html' %}

{%block scripts%}
    {{block.super}}
    <script>
        $(document).ready(function() {
            $("#technologysearch").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $('div[data-searchable="true"]').filter(function() {
                    $(this).toggle($(this).find('.searchable-text').text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
{%endblock scripts%}

{%block styles%}
    {{block.super}}
    <style>
        

    .filter-card {
        max-width: 375px;
    }
    </style>
{%endblock styles%}

{% block home_nav_active %}active{%endblock home_nav_active%}


{%block content%}
    <div class="row mt-5" >
        <div class="col center" >
        </div>
        <div class="col center" >
            <a style="font-family:Roboto-Bold;">Buzzword Search</a>
            <input class="filter-form-control form-control mr-sm-2 center" type="search" placeholder="Enter a Language, Technology or Project" aria-label="Search" id="technologysearch" >
        </div>
        <div class="col center" >
        </div>
        {% comment %} <div class="col">
        </div> {% endcomment %}
    </div>
    <div class="layout-margin-8 mt-5">
        <div class="row">
            {%for technology in technologies%}
                <div class="col-sm pb-3" style="max-width:347.982px" id="technology-{{technology.pk}}" data-searchable="true">
                    <div class="card filter-card h-100">
                        <div style="height:100px">
                            <a href="{% url 'projects' technology_id=technology.pk %}"><img class="img-top" src="/media/{{technology.image}}"></a>
                        </div>
                        <div class="card-body">
                            <h5 class="filter-card-title searchable-text"><a href="{% url 'projects' technology_id=technology.pk %}">{{technology.name}} {% if request.user.is_superuser %} <a href="/admin/core/technology/{{technology.pk}}/change/" target="_blank" style="color:green"><i class="fas fa-edit"></i> Edit</a> {% endif %}</a></h5> 
                            <p class="card-text">
                                {% if technology.project_set.all %}
                                    <span>Projects:</span><br>
                                    <ul>
                                        {% for project in technology.project_set.all %}
                                            <li> 
                                                <a href="{% url 'project' project_id=project.pk %}" class="searchable-text">{{project.name}}</a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </p>
                        </div>
                        <div class="card-footer text-muted text-truncate">
                            {% for language in technology.language.all %}
                                <a href="{% url 'projects' language_id=language.pk %}"><span class="badge badge-primary searchable-text">{{language.name}}</span></a>
                            {% endfor %}
                            {% for type in technology.type.all %}
                                <span class="badge badge-secondary searchable-text">{{type.name}}</span>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {%endfor%}
            {% if request.user.is_superuser %}
                <div class="col-sm pb-3" id="technology-{{technology.pk}}" data-searchable="true">
                    <div class="card filter-card h-100">
                        <div class="card-body">
                            <h5 class="filter-card-title searchable-text"><a href="/admin/core/technology/add/" target="_blank" style="color:green"><i class="fas fa-plus-circle"></i> Add</a></h5>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{%endblock content%}

templates/core/iot.html
{% extends 'core/base.html' %}

{%block scripts%}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    {{block.super}}
    <script>
        $(document).ready(function() {
            $(function () {
                var $energyChart = $("#energy-chart");
                var respStatus = $.ajax({
                    url: $energyChart.data("url"),
                    success: function (data) {

                        var ctx = $energyChart[0].getContext("2d");

                        new Chart(ctx, {
                            type: 'bar',
                            data: {
                            labels: data.labels,
                            datasets: [{
                                label: 'Watt Hours consumed',
                                backgroundColor: 'blue',
                                data: data.data
                            }]          
                            },
                            options: {
                            responsive: true,
                            legend: {
                                position: 'top',
                            },
                            title: {
                                display: true,
                                text: 'Desktop PC Energy Consumption'
                            }
                            }
                        });

                    }
                });

            });
        });

    </script>
    <script>

        

    </script>
{%endblock scripts%}

{%block styles%}
    {{block.super}}
    <style>
    </style>
{%endblock styles%}

{% block iot_nav_active %}active{%endblock iot_nav_active%}

{%block content%}
    <div class="layout-margin-custom">
        <div class="row"> 
            <div id="container" style="width: 75%;">
                
            </div>
        </div>
    </div>

    <div class="layout-margin-8 mt-5">
        <div class="row">
            <div class="col-sm pb-6" style="" id="technology-{{technology.pk}}" data-searchable="true">
                <div class="card filter-card ">
                    <canvas id="energy-chart" data-url="{% url 'energy-chart' %}"></canvas>
                </div>
            </div>
            <div class="col-sm pb-6" style="" id="technology-{{technology.pk}}" data-searchable="true">
                <div class="card filter-card ">
                </div>
            </div>
        </div>
    </div>
{%endblock content%}

templates/core/project.html
{% extends 'core/base.html' %}

{%block scripts%}
    {{block.super}}
    <script>
        $(document).ready(function() {
            $('img[data-enlargeable]').addClass('img-enlargeable').click(function() {
                var src = $(this).attr('src');
                var modal;
              
                function removeModal() {
                  modal.remove();
                  $('body').off('keyup.modal-close');
                }
                modal = $('<div>').css({
                  background: 'RGBA(0,0,0,.5) url(' + src + ') no-repeat center',
                  backgroundSize: 'contain',
                  width: '100%',
                  height: '100%',
                  position: 'fixed',
                  zIndex: '10000',
                  top: '0',
                  left: '0',
                  cursor: 'zoom-out'
                }).click(function() {
                  removeModal();
                }).appendTo('body');
                //handling ESC
                $('body').on('keyup.modal-close', function(e) {
                  if (e.key === 'Escape') {
                    removeModal();
                  }
                });
              });
        });

    </script>
{%endblock scripts%}

{%block styles%}
    {{block.super}}
    <style>

        .image-modal-dialog {
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
        }

        .image-modal-content {
            height: auto;
            min-height: 100%;
            border-radius: 10px;
            background: #d3d3d3;
        }

        .modal-backdrop {
            background-color: rgba(0,0,0,1) !important;
        }

        .image-modal-dialog {
            max-width: none;
        }

        #image-modal {
            padding:20px 40px 20px 40px;
            margin: auto;

        }

        .card-img-top{
        }

        .projectimage {
        }

        .container{
            width:100%;
            padding:0px;
            margin:0px;
            max-width:none;
        }
    </style>
{%endblock styles%}

{% block projects_nav_active %}active{%endblock projects_nav_active%}

{%block content%}
    <div class="layout-margin-custom">
        <div class="row">    
            <div class="col">    
                <div class="card main-card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col pl-0">
                                Project - <span style="font-family:Roboto-Bold">{{project.name}}</span>                        
                                {% if request.user.is_superuser %}
                                    <a href="/admin/core/project/{{project.pk}}/change/" target="_blank" style="color:green" class="nowrap"> <i class="fas fa-edit"></i> Edit</a>
                                {% endif %}
                            </div>
                            <div class="col" style="text-align:right">
                                <a href="/projects">Back to Project List</a>
                            </div>
                        </div>
                        
                    </div>
                    <div class="card-body">
                        {{project.htmldescription|safe}} 
                    </div>
                </div>
            </div>
        </div>
        <br>
        {%if project.projectimage_set.all%}
        <div class="row">     
            <div class="col">    
                <div class="card main-card">
                    <div class="row">
                        {%for projectimage in project.projectimage_set.all%}
                        <div class="col-xl-3 col-lg-4 col-md-6 mb-4">
                            <div class="bg-white rounded shadow-sm projectimage">
                                <img src="/media/{{projectimage.image}}" id="projectimage-{{projectimage.pk}}"style="cursor: zoom-in" data-enlargeable alt="" class="img-fluid card-img-top">
                              <div class="p-4">
                                <p class="small text-muted mb-0">{{projectimage.htmldescription|safe}}</p>
                                  <p class="small mb-0"><i class="fa fa-picture-o mr-2"></i></p>
                                  <a href="/project/image/{{projectimage.pk}}" class="badge badge-primary px-3 rounded-pill font-weight-normal">Download</a>
                                  {% if request.user.is_superuser %}
                                      <a href="/admin/core/projectimage/{{projectimage.pk}}/change/" target="_blank" class="badge badge-primary px-3 rounded-pill font-weight-normal">Edit</a>
                                  {% endif %}
                              </div>
                            </div>
                        </div>
                        {%endfor%}
                        {% if request.user.is_superuser %}
                        <div class="col-xl-3 col-lg-4 col-md-6 mb-4">
                            <div class="bg-white rounded shadow-sm projectimage">
                                <h5 class="filter-card-title searchable-text"><a href="/admin/core/projectimage/add/" target="_blank" style="color:green"><i class="fas fa-plus-circle"></i> Add</a></h5>
                            </div>
                        </div>
                        {%endif%}
                    </div>
                </div>
            </div>
        </div>
        {%else%}
        {% if request.user.is_superuser %}
        <div class="row">     
            <div class="col">    
                <div class="card main-card">
                    <div class="row">
                        <div class="col-xl-3 col-lg-4 col-md-6 mb-4">
                            <div class="bg-white rounded shadow-sm projectimage">
                                <h5 class="filter-card-title searchable-text"><a href="/admin/core/projectimage/add/" target="_blank" style="color:green"><i class="fas fa-plus-circle"></i> Add</a></h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {%endif%}
        {%endif%}
    </div>
{%endblock content%}